/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicafinal_ad;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author xp
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    DefaultTableModel mostrar;
    String error = "";
    
    public interfaz() {
        initComponents();
        this.getContentPane().setBackground(Color.gray);
        try {
            gc.conect.setAutoCommit(false);

            Statement sta = gc.conect.createStatement();

            String query = "SELECT * FROM album ";

            ResultSet rs = sta.executeQuery(query);
            ResultSetMetaData metaDatos = rs.getMetaData();

            int numColumnas = metaDatos.getColumnCount();

            DefaultTableModel modelo = new DefaultTableModel();

            this.jTable1.setModel(modelo);

            for (int i = 1; i <= numColumnas; i++) {
                modelo.addColumn(metaDatos.getColumnLabel(i));
            }

            while (rs.next()) {
                Object[] fila = new Object[numColumnas];

                for (int i = 0; i < numColumnas; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Consulta_idcancion = new javax.swing.JButton();
        numero_cancion = new javax.swing.JTextField();
        titulo = new javax.swing.JLabel();
        Consulta_idalbum = new javax.swing.JButton();
        Consulta_albumes = new javax.swing.JButton();
        numero_album = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Consulta_canciones = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label_titulo = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();
        label_duracion = new javax.swing.JLabel();
        id_letra = new javax.swing.JLabel();
        label_idAlbum = new javax.swing.JLabel();
        Text_titulo = new javax.swing.JTextField();
        Text_id = new javax.swing.JTextField();
        Text_duracion = new javax.swing.JTextField();
        Text_letra = new javax.swing.JTextField();
        Text_idAlbum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        label_id2 = new javax.swing.JLabel();
        label_Nombre = new javax.swing.JLabel();
        label_anno = new javax.swing.JLabel();
        Texto_id2 = new javax.swing.JTextField();
        Texto_iNombre = new javax.swing.JTextField();
        Texto_anno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Consulta_idcancion.setText("Consulta id de Canciones");
        Consulta_idcancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta_idcancionActionPerformed(evt);
            }
        });

        numero_cancion.setText(" 1");
        numero_cancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_cancionActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(51, 255, 204));
        titulo.setText("        DISCOGRAFICA");
        titulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Consulta_idalbum.setText("Consulta id de Album");

        Consulta_albumes.setText("Consulta Albumes ");
        Consulta_albumes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta_albumesActionPerformed(evt);
            }
        });

        numero_album.setText(" 1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        Consulta_canciones.setText("Consulta Canciones");
        Consulta_canciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta_cancionesActionPerformed(evt);
            }
        });

        jButton1.setText("Añadir Columna");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Inserta una Cancion:");

        label_titulo.setText("Titulo");

        label_id.setText("ID:");

        label_duracion.setText("Duracion:");

        id_letra.setText("Letra:");

        label_idAlbum.setText("ID album:");

        Text_titulo.setPreferredSize(null);

        Text_id.setPreferredSize(null);
        Text_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_idActionPerformed(evt);
            }
        });

        Text_duracion.setPreferredSize(null);
        Text_duracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_duracionActionPerformed(evt);
            }
        });

        Text_letra.setPreferredSize(null);

        Text_idAlbum.setPreferredSize(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Inserta un Album:");

        label_id2.setText("ID:");

        label_Nombre.setText("Nombre:");

        label_anno.setText("Año:");

        Texto_anno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Texto_annoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_id, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_duracion)
                                    .addComponent(id_letra, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_idAlbum))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Text_idAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Text_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(Text_id, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Text_letra, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Texto_anno, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(label_id2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(label_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(label_anno, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(Texto_iNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Texto_id2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addContainerGap())))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Text_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Consulta_albumes, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(Consulta_canciones, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(Consulta_idcancion, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numero_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Consulta_idalbum, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(numero_album, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Consulta_idalbum)
                    .addComponent(numero_album, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Consulta_idcancion))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consulta_albumes)
                    .addComponent(Consulta_canciones)
                    .addComponent(jButton1))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_titulo)
                            .addComponent(Text_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_id)
                                    .addComponent(Text_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_duracion)
                                    .addComponent(Text_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_letra)
                            .addComponent(Text_letra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_id2)
                            .addComponent(Texto_id2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_Nombre)
                            .addComponent(Texto_iNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_anno)
                            .addComponent(Texto_anno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_idAlbum)
                    .addComponent(Text_idAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Consulta_idcancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta_idcancionActionPerformed
        // TODO add your handling code here:
        try {
                gc.conect.setAutoCommit(false);
                
                String ID = numero_cancion.getText();

                String query = "SELECT * FROM cancion WHERE id_cancion like "+ ID;
                Statement sta = gc.conect.createStatement();
    
                ResultSet rs = sta.executeQuery(query);
                
                ResultSetMetaData metaDatos = rs.getMetaData();

                int numColumnas = metaDatos.getColumnCount();

                mostrar = new DefaultTableModel();

                this.jTable1.setModel(mostrar);

                for (int i = 1; i <= numColumnas; i++) {
                    mostrar.addColumn(metaDatos.getColumnLabel(i));
                }

                while (rs.next()) {
                    Object [] fila = new Object[numColumnas];

                    for (int i = 0; i < numColumnas; i++) {
                        fila [i] = rs.getObject(i +1);
                    }
                    mostrar.addRow(fila);
                }

                rs.close();
                sta.close();
  
            } catch (Exception e) {
                e.printStackTrace();
             
            
            }
    }//GEN-LAST:event_Consulta_idcancionActionPerformed

    private void numero_cancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_cancionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero_cancionActionPerformed

    private void Consulta_albumesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta_albumesActionPerformed
        // TODO add your handling code here:
        try {
            gc.conect.setAutoCommit(false);

            String query = "SELECT * FROM album ";

            Statement sta = gc.conect.createStatement();

            ResultSet rs = sta.executeQuery(query);
            ResultSetMetaData metaDatos = rs.getMetaData();

            int numColumnas = metaDatos.getColumnCount();

             mostrar = new DefaultTableModel();

            this.jTable1.setModel(mostrar);

            for (int i = 1; i <= numColumnas; i++) {
                mostrar.addColumn(metaDatos.getColumnLabel(i));
            }

            while (rs.next()) {
                Object [] fila = new Object[numColumnas];

                for (int i = 0; i < numColumnas; i++) {
                    fila [i] = rs.getObject(i +1);
                }
                mostrar.addRow(fila);
            }
            
            rs.close();

            sta.close();
        } catch (Exception e) {
            e.printStackTrace();
            error = e.toString();
            
        }
    }//GEN-LAST:event_Consulta_albumesActionPerformed

    private void Text_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_idActionPerformed

    private void Text_duracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_duracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_duracionActionPerformed

    private void Texto_annoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Texto_annoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Texto_annoActionPerformed

    private void Consulta_cancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta_cancionesActionPerformed
        // TODO add your handling code here:
         try {
            gc.conect.setAutoCommit(false);

            String query = "SELECT * FROM cancion ";

            Statement sta = gc.conect.createStatement();

            ResultSet rs = sta.executeQuery(query);
            ResultSetMetaData metaDatos = rs.getMetaData();

            int numColumnas = metaDatos.getColumnCount();

            mostrar = new DefaultTableModel();

            this.jTable1.setModel(mostrar);

            for (int i = 1; i <= numColumnas; i++) {
                mostrar.addColumn(metaDatos.getColumnLabel(i));
            }

            while (rs.next()) {
                Object [] fila = new Object[numColumnas];

                for (int i = 0; i < numColumnas; i++) {
                    fila [i] = rs.getObject(i +1);
                }
                mostrar.addRow(fila);
            }

            rs.close();

            sta.close();
        } catch (Exception e) {
            e.printStackTrace();
            error = e.toString();
        }
                                                                                                
               
    }//GEN-LAST:event_Consulta_cancionesActionPerformed

    /**
     * @param args the command line arguments
     */
    GestorConexion gc = new GestorConexion();
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Consulta_albumes;
    private javax.swing.JButton Consulta_canciones;
    private javax.swing.JButton Consulta_idalbum;
    private javax.swing.JButton Consulta_idcancion;
    private javax.swing.JTextField Text_duracion;
    private javax.swing.JTextField Text_id;
    private javax.swing.JTextField Text_idAlbum;
    private javax.swing.JTextField Text_letra;
    private javax.swing.JTextField Text_titulo;
    private javax.swing.JTextField Texto_anno;
    private javax.swing.JTextField Texto_iNombre;
    private javax.swing.JTextField Texto_id2;
    private javax.swing.JLabel id_letra;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label_Nombre;
    private javax.swing.JLabel label_anno;
    private javax.swing.JLabel label_duracion;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_id2;
    private javax.swing.JLabel label_idAlbum;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JTextField numero_album;
    private javax.swing.JTextField numero_cancion;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
